### PR TITLE
fix mentions breaking out of links

### PR DESCRIPTION
**Pull request by BenLubar**
Also fix mentions inside code blocks being replaced when another mention of the same user was in the same post.

https://github.com/apapadimoulis/what-bugs/issues/93
https://github.com/apapadimoulis/what-bugs/issues/121
https://github.com/julianlam/nodebb-plugin-mentions/issues/69
https://github.com/julianlam/nodebb-plugin-mentions/issues/71

### CODE REVIEW

**Comment by julianlam** [comment]
:clap:

**Comment by julianlam** [comment]
What's the raw input that this PR fixes?

**Comment by BenLubar** [comment]
```
    @julianlam
    ```
    
    @julianlam

and

    user said in [@julianlam made a plugin](/post/1234)

**Comment by julianlam** [comment]
v1.1.2 and nodebb/nodebb@01aeb45

**Pull request merged**
