### PR TITLE
Fix: mention group not in English

### PR DESCRIPTION
**Pull request by MegaGM**
So, I've made a simple fix.

### CODE REVIEW

**Comment by julianlam** [comment]
v0.10.0

**Comment by MegaGM** [comment]
@julianlam Please update the version in npm too.
each time I do ` ./nodebb upgrade ` it reverts back to @0.9.1 
http://i.imgur.com/gTGOpYF.png
I know, there is ` npm i nodebb-plugin-mentions@0.10.0 ` but, Julian, please :3

**Comment by julianlam** [comment]
https://www.npmjs.com/package/nodebb-plugin-mentions

Latest is published, try to clear your npm cache?

**Comment by MegaGM** [comment]
Sorry, but I can't understand what I'm doing wrong..
1. ` cd ~/.npm && ls ` there is a bunch of folders
1. ` npm cache clean `
1. ` cd ~/.npm && ls ` there is no folders anymore
1. ` cd path/to/nodebb && ./nodebb upgrade ` and I get exactly what is on screenshot, @0.9.1 
I know this question kinda isn't strictly related to NodeBB at all, but, could you tell me please, what I'm doing wrong?

**Pull request merged**
