### PR TITLE
don't send notifications to mentioned users that are ignoring the topic

### PR DESCRIPTION
**Pull request by BenLubar**
Closes apapadimoulis/what-bugs#126

### CODE REVIEW

**Comment by AccaliaDeElementia** [comment]
This should be configurable per user.

*i* for one want mention notifications, even if i told nodebb to stop telling me about new posts in the thread.

**Comment by BenLubar** [comment]
Ignoring is one step further than not-watching.

**Comment by AccaliaDeElementia** [comment]
Not exactly.

if I ignore a topic right now it stops showing up as unread but i can still participate when i am mentioned or interacted with.

what blakey wants is a mute option. which should be separate from ignore.

**Comment by AccaliaDeElementia** [comment]
or if not separate then switchable so the user can choose if their ignore means `ignore` or `mute`

that option's probably less work and less testing.

**Comment by BenLubar** [comment]
Wouldn't we end up with three different spellings of "don't notify me about this thread" that all mean different things?

**Comment by AccaliaDeElementia** [comment]
we had four statuses in discourse.

i see no problems with that here.

but if you do then a user option to `suppress notifications from ignored topics` would work too.

**Comment by julianlam** [comment]
Bit of a back-and-forth here, but ultimately I am in favour of merging. If you're explicitly ignored a topic, then it stands to reason you probably don't want to be notified of any pings therein either.

Will merge if no other objections.

**Comment by julianlam** [comment]
Better late than never :shipit:

**Pull request merged**
