### PR TITLE
Dont send mentions of ignored users 

### PR DESCRIPTION
**Pull request by exomarty**
Check if user who mention is ignored by mentioned user
Compatible with Ignore Users plugin

https://github.com/exo-do/nodebb-plugin-ignore-users

### CODE REVIEW

**Comment by martyalicante** [comment]
yes, no , maybe?

**Comment by julianlam** [comment]
I wasn't aware we could ignore users in NodeBB :smile: 

My apologies on the delayed response, I had no idea this PR was even open!

**Comment by barisusakli** [comment]
Core doesn't have ignore users, it's a plugin apparently

**Comment by julianlam** [comment]
Hi @exomarty -- best bet is to subscribe to the hooks fired during notification push: https://github.com/NodeBB/NodeBB/blob/master/src/notifications.js#L227

This is an action, although perhaps you may want a filter prior to the push? If so, open up a new issue in main repo :smile:

**Pull request closed without merging**
