### PR TITLE
fix group mentions

### PR DESCRIPTION
**Pull request by barisusakli**

### CODE REVIEW

**Comment by julianlam** [comment]
Looks good (I hope). Needs update to `package.json` to require `0.6.1`

**Comment by barisusakli** [comment]
I think package.json already has 
```
"nbbpm": {
    "compatibility": "^0.6.1"
  }
```

**Comment by julianlam** [comment]
Thanks, testing..

**Comment by julianlam** [comment]
Works great, publishing.

**Comment by julianlam** [comment]
0.9.0

**Pull request merged**
